from fortress_inventory.entity_graph import InventoryEntityGraph, InventoryEntityGraphError


GENERATED_CADDY_ROUTES_PATH = "/etc/caddy/fortress/generated-routes.caddy"
GENERATED_DNSMASQ_INGRESS_RECORDS_PATH = "pihole/etc-dnsmasq.d/99-fortress-ingress.conf"
GENERATED_FILE_HEADER = "# Generated by fortress ingress regeneration. Do not edit by hand."


def build_caddy_route_model(model):
    graph = InventoryEntityGraph(model)
    routes = []
    routes.extend(_service_routes(model, graph))
    routes.extend(_host_ingress_routes(model, graph))
    routes = sorted(routes, key=lambda route: route["hostname"])
    return {
        "ingress_address": _ingress_address(model, graph) if routes else None,
        "routes": routes,
    }


def render_caddy_routes(model):
    route_model = build_caddy_route_model(model)
    return "\n\n".join(_render_caddy_route(route) for route in route_model["routes"]) + "\n"


def render_ingress_dns_record_sets(model):
    route_model = build_caddy_route_model(model)
    content = _render_dnsmasq_ingress_records(route_model)
    return [
        {
            "service": target["service"],
            "provider": target["provider"],
            "backend_vm": target["backend_vm"],
            "path": f"/srv/services/{target['service']}/{GENERATED_DNSMASQ_INGRESS_RECORDS_PATH}",
            "write_mode": "replace",
            "content": content,
        }
        for target in ingress_dns_targets(model)
    ]


def ingress_dns_targets(model):
    graph = InventoryEntityGraph(model)
    targets = []
    for service_name, service in model.services.items():
        dns = service.get("dns") or {}
        if not dns.get("ingress_records", {}).get("enabled"):
            continue
        targets.append(
            {
                "service": service_name,
                "provider": dns.get("provider"),
                "backend_vm": graph.service_backend_vm_name(service_name),
            }
        )
    return sorted(targets, key=lambda target: target["service"])


def _render_dnsmasq_ingress_records(route_model):
    lines = [GENERATED_FILE_HEADER]
    ingress_address = route_model["ingress_address"]
    for route in route_model["routes"]:
        lines.append(f"address=/{route['hostname']}/{ingress_address}")
    return "\n".join(lines) + "\n"


def _service_routes(model, graph):
    routes = []
    for service_name in graph.ingress_enabled_service_names():
        service = model.services[service_name]
        backend_vm_name = graph.service_backend_vm_name(service_name)
        if backend_vm_name not in model.vms:
            continue
        routes.append(
            {
                "kind": "service",
                "hostname": service.get("hostname"),
                "target": _http_target(
                    _required_vm_static_ipv4_address(
                        graph,
                        backend_vm_name,
                        f"Backend VM {backend_vm_name}",
                    ),
                    graph.service_backend_port(service_name),
                ),
                "owner": service_name,
                "tls": service.get("ingress", {}).get("tls"),
            }
        )
    return routes


def _host_ingress_routes(model, graph):
    routes = []
    trusted_source_ranges = _trusted_source_ranges(model)
    for host_name in graph.host_ingress_route_names():
        host = model.hosts[host_name]
        route = host.get("ingress", {}).get("proxmox_web_ui", {})
        routes.append(
            {
                "kind": "host",
                "hostname": route.get("hostname"),
                "target": _http_target(
                    _required_host_management_ipv4_address(
                        graph,
                        host_name,
                        f"Host Ingress Route {host_name}",
                    ),
                    route.get("port", 8006),
                ),
                "trusted_source_ranges": trusted_source_ranges,
                "owner": host_name,
                "tls": route.get("tls", "letsencrypt_dns"),
            }
        )
    return routes


def _render_caddy_route(route):
    if route["kind"] == "host":
        source_ranges = " ".join(route["trusted_source_ranges"])
        return "\n".join(
            [
                f"{route['hostname']} {{",
                _render_tls(route),
                f"\t@trusted remote_ip {source_ranges}",
                "\thandle @trusted {",
                f"\t\treverse_proxy {route['target']}",
                "\t}",
                "\trespond 403",
                "}",
            ]
        )

    return "\n".join(
        [
            f"{route['hostname']} {{",
            _render_tls(route),
            f"\treverse_proxy {route['target']}",
            "}",
        ]
    )


def _render_tls(route):
    if route.get("tls") == "letsencrypt_dns":
        return "\n".join(
            [
                "\ttls {",
                "\t\tdns cloudflare {$CLOUDFLARE_API_TOKEN}",
                "\t}",
            ]
        )
    return "\ttls internal"


def _http_target(address, port):
    return f"http://{address}:{port}"


def _trusted_source_ranges(model):
    return list((model.globals.get("ingress") or {}).get("trusted_source_ranges") or [])


def _ingress_address(model, graph):
    vm_name = graph.service_backend_vm_name("internal-ingress")
    vm = model.vms.get(vm_name)
    if not vm:
        raise ValueError("Ingress VM internal-ingress backend is not declared")
    return _required_vm_static_ipv4_address(graph, vm_name, f"Ingress VM {vm_name}")


def _required_vm_static_ipv4_address(graph, vm_name, label):
    addresses = graph.vm_static_ipv4_addresses(vm_name)
    if len(addresses) != 1:
        raise InventoryEntityGraphError(f"{label} must declare exactly one static IPv4 address")
    return addresses[0]


def _required_host_management_ipv4_address(graph, host_name, label):
    address = graph.host_management_ipv4_address(host_name)
    if not address:
        raise InventoryEntityGraphError(f"{label} must declare a management IPv4 address")
    return address
