from ipaddress import ip_interface


GENERATED_CADDY_ROUTES_PATH = "/etc/caddy/fortress/generated-routes.caddy"
GENERATED_DNSMASQ_INGRESS_RECORDS_PATH = "/etc/dnsmasq.d/99-fortress-ingress.conf"
GENERATED_FILE_HEADER = "# Generated by fortress ingress regeneration. Do not edit by hand."


def build_caddy_route_model(model):
    routes = []
    routes.extend(_service_routes(model))
    routes.extend(_host_ingress_routes(model))
    routes = sorted(routes, key=lambda route: route["hostname"])
    return {
        "ingress_address": _ingress_address(model) if routes else None,
        "routes": routes,
    }


def render_caddy_routes(model):
    route_model = build_caddy_route_model(model)
    return "\n\n".join(_render_caddy_route(route) for route in route_model["routes"]) + "\n"


def render_ingress_dns_record_sets(model):
    route_model = build_caddy_route_model(model)
    content = _render_dnsmasq_ingress_records(route_model)
    return [
        {
            "service": target["service"],
            "provider": target["provider"],
            "backend_vm": target["backend_vm"],
            "path": GENERATED_DNSMASQ_INGRESS_RECORDS_PATH,
            "write_mode": "replace",
            "content": content,
        }
        for target in ingress_dns_targets(model)
    ]


def ingress_dns_targets(model):
    targets = []
    for service_name, service in model.services.items():
        dns = service.get("dns") or {}
        if not dns.get("ingress_records", {}).get("enabled"):
            continue
        targets.append(
            {
                "service": service_name,
                "provider": dns.get("provider"),
                "backend_vm": service.get("backend", {}).get("vm"),
            }
        )
    return sorted(targets, key=lambda target: target["service"])


def _render_dnsmasq_ingress_records(route_model):
    lines = [GENERATED_FILE_HEADER]
    ingress_address = route_model["ingress_address"]
    for route in route_model["routes"]:
        lines.append(f"address=/{route['hostname']}/{ingress_address}")
    return "\n".join(lines) + "\n"


def _service_routes(model):
    routes = []
    for service_name, service in model.services.items():
        if not service.get("ingress", {}).get("enabled"):
            continue
        backend = service.get("backend", {})
        vm = model.vms.get(backend.get("vm"))
        if not vm:
            continue
        routes.append(
            {
                "kind": "service",
                "hostname": service.get("hostname"),
                "target": f"http://{_unambiguous_vm_ipv4(vm, f'Backend VM {backend.get('vm')}')}:{backend.get('port')}",
                "owner": service_name,
                "tls": service.get("ingress", {}).get("tls"),
            }
        )
    return routes


def _host_ingress_routes(model):
    routes = []
    trusted_source_ranges = _trusted_source_ranges(model)
    for host_name, host in model.hosts.items():
        route = host.get("ingress", {}).get("proxmox_web_ui", {})
        if not route.get("enabled"):
            continue
        routes.append(
            {
                "kind": "host",
                "hostname": route.get("hostname"),
                "target": f"http://{_host_management_ipv4(host, host_name)}:{route.get('port', 8006)}",
                "trusted_source_ranges": trusted_source_ranges,
                "owner": host_name,
                "tls": route.get("tls", "letsencrypt_dns"),
            }
        )
    return routes


def _render_caddy_route(route):
    if route["kind"] == "host":
        source_ranges = " ".join(route["trusted_source_ranges"])
        return "\n".join(
            [
                f"{route['hostname']} {{",
                _render_tls(route),
                f"\t@trusted remote_ip {source_ranges}",
                "\thandle @trusted {",
                f"\t\treverse_proxy {route['target']}",
                "\t}",
                "\trespond 403",
                "}",
            ]
        )

    return "\n".join(
        [
            f"{route['hostname']} {{",
            _render_tls(route),
            f"\treverse_proxy {route['target']}",
            "}",
        ]
    )


def _render_tls(route):
    if route.get("tls") == "letsencrypt_dns":
        return "\n".join(
            [
                "\ttls {",
                "\t\tdns cloudflare {$CLOUDFLARE_API_TOKEN}",
                "\t}",
            ]
        )
    return "\ttls internal"


def _trusted_source_ranges(model):
    return list((model.globals.get("ingress") or {}).get("trusted_source_ranges") or [])


def _ingress_address(model):
    service = model.services.get("internal-ingress")
    vm_name = (service or {}).get("backend", {}).get("vm")
    vm = model.vms.get(vm_name)
    if not vm:
        raise ValueError("Ingress VM internal-ingress backend is not declared")
    return _unambiguous_vm_ipv4(vm, f"Ingress VM {vm_name}")


def _unambiguous_vm_ipv4(vm, label):
    addresses = []
    for interface in vm.get("network", {}).get("interfaces", []) or []:
        address = interface.get("address")
        if not address:
            continue
        parsed = ip_interface(address)
        if parsed.version == 4:
            addresses.append(str(parsed.ip))
    if len(addresses) != 1:
        raise ValueError(f"{label} must declare exactly one static IPv4 address")
    return addresses[0]


def _host_management_ipv4(host, host_name):
    address = host.get("network", {}).get("management_address")
    if not address:
        raise ValueError(f"Host Ingress Route {host_name} must declare a management IPv4 address")
    parsed = ip_interface(address)
    if parsed.version != 4:
        raise ValueError(f"Host Ingress Route {host_name} must declare a management IPv4 address")
    return str(parsed.ip)
