ssh_keys:
    bootstrap:
        type: ENC[AES256_GCM,data:opI+o6FJzG8=,iv:6WGhnI/L3K3tkDxm8qRxrdettnHB4suIiBpR7iRpu/E=,tag:EPhkaPikemfaOCtFpaqmtA==,type:str]
        created: ENC[AES256_GCM,data:chjHXwlRzFYxAyZV5/6vIio9QXc=,iv:id09G6Z0fG5+GDIwSZ5VMtqAwwx+xB+HJmKyjSfHrLU=,tag:jN8iYgWsTkcWP2I2g5EX+w==,type:time]
        public_key: ENC[AES256_GCM,data:fQ7kIQfW1+Y+c+vIG3XRCnBZe2tH2Kgb8x2nXz2M8wMeia+MuzvJ5AtjquKUYUvKctxJP5mlS+4NO8gXHOeTPG/kahGCMF56IRx9gzmFmdGN35M/4aughnUftSoZnCO5qnvF87JXyBumdbDsAETxu9xSFeSjsz7Zkt/y53Ao8mY0WK4=,iv:gsgJdPWesANjejXKn/v8Tsyhoh6609Ha4917VQqBKVY=,tag:MACOU+kbzPDz0QytaXuUeA==,type:str]
        private_key: ENC[AES256_GCM,data:H99dZZEijKTp+uNL6VK/C5HKfpaIRCbZTFYk+bgig16dUC/HRcKWFoKFo15A9QC7KoUWzGHwjqeWA8UyT4OeumRNHB3rXRc+89/5QLFuzAL3HpNJyXWtkdWcRmP7W3EVPI4j5cxrooRmbS/oUYEYNprNb5gyR63Li3b27gyYvfd29WpooReYfJNeWs2nzK3S+pZoO4LI1ytlmpGPED8jmZTgQTMcWmbXUndFoLRGcuE5YR7kuQZjmVf/7US4NBvhLaCHUk3FM4zQ6rTr9Z2MIsTMqynhX6BgpjR4sOlAtxV+/GHi45xbgj41inoMj6ALmRJ7/wuXk1aeUfJPQ4ep81fq2LD1ZIP0MG3RTSZWvsX3dOB61VwmxtianHnnEkpMt1cb5i45BTCaRPmj8vbKbUb7UnOJbbobe3hALzjbH9audeJfa8/yjzbYuSz9yuzBgzFoXYUC9bBYTZGS3QqtnkT6f13XoqCViNVM3dosB5fJ9Fm6H3z9u7aqg8JR03gwSRi0c3dsky0jYmsn9NGT7I2zNjLf7YByn2+5fxHRHkInZFEzNt3R0aTAmxPG/zEkDPW0v4AwduZeE8PyaSXEDb7gc9s=,iv:CHAyTILemqMBRNnC0wqMcUnqtwc5Cz8jBXBDAmyORlo=,tag:VgYiTFzdf1pd40+Y3ozyQg==,type:str]
pve_tokens:
    tofu:
        user: ENC[AES256_GCM,data:G6dagJnpgeA=,iv:ZT08/38WRJQN+Yacb9ObeOCZtMy2fvHMEwVD5VDmbNY=,tag:o1xB28HiKXReVnxqV61EQA==,type:str]
        token_id: ENC[AES256_GCM,data:tfi7XQ==,iv:ryPdiAE6YHIOpJsSCumyCQ47F3qc3AfypKOJftQ0Zus=,tag:PNA+tawxlRXb32FMUGlj3A==,type:str]
        value: ENC[AES256_GCM,data:Fp6mL4Z05X5AoRGtDX30zK9VDjcE0y5RUI4Gks5RGoHa9Z/1,iv:T4vVQPgMdDkrgObde31auS03AK09t6xbIwvm4lk8iZo=,tag:+jwvSlv7+EPPI7ool1f34A==,type:str]
sops:
    age:
        - recipient: age1uy27rg7l9ql0z5uze4m969sarzl3dhjlzsty9g6xsl4542kh9yzqsleu5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcmJoTDlmQUpqM3hlYkY1
            U1JHblBwOGkrVzBDZk4vSmQzVzFGSGJMUlJzClhoNUl5Z2JCbU8xek0vSS9HVllC
            SjAzazR4RFVLa0c2RG9Oa0FyRnoyVGsKLS0tIHBVQlpvWkovTHFEZUlmVWpRWnlz
            VURPaXNvdnhBUUtad2V1MjdSeTR1NFkK0hp7dqYZBEyoA5ipFVKBe0d4LOS1K0lK
            JDA5w28jMvLM8kNHbmLWSvLeAWYMBYrwPu1PGvYN2W/7ipcQP9dX5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T16:57:44Z"
    mac: ENC[AES256_GCM,data:liuWCEqzar+Zcy+asma3s9N2QjAnTo44Qjdm4mrSBucN/8kKp8qWUpy617JjoqsvGDKElgAjPG8Sp6wEEK5hkmE32kpSF1UHms4j4qip0swpqmJO1FR6pAcRxedplg8ECV6op2UaOqgK7NrEs1ltIaErodk6OMRxBsrlPFBPyi0=,iv:N9MRpCte2PIMRYY7psr+ZiW93y+Uct+0dfGUwuOscyg=,tag:RKubjqxgfK2+a+Gxq7Ofbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
