proxmox:
  pve_node_name: neuromancer
  endpoint: http://10.10.0.12:8006
  # endpoint: https://neuromancer.fearn.cloud:8006
  templates:
    - debian-13-base
  users:
    - name: tofu@pve
      roles: [PVEVMAdmin, PVEDatastoreUser]
      tokens:
        - id: tofu
          roles: [PVEVMAdmin, PVEDatastoreUser]
hardware:
  cpu: i7-8700T
  cores: 12
  memory_gb: 32
  storage:
    - name: local-lvm
      kind: lvmthin
    - name: local
      kind: directory
network:
  management_address: 10.10.0.13
  bridges:
    - name: vmbr0
      managed: false
      vlan: 10
      cidr: 10.10.0.13/24
      gateway: 10.10.0.1
gpu_passthrough:
  enabled: true
  vendor: intel
  mode: full
  iommu: intel
  blacklist_host_driver: true
