ssh_keys:
    bootstrap:
        type: ENC[AES256_GCM,data:n0kl2Wo2,iv:2UWgordc8TyvIujSYhMUC0cxsawVN4i6q9FxFzuUxhM=,tag:dKGG/toWSlygfyTSjUYgIw==,type:str]
        created: ENC[AES256_GCM,data:5vbuXQXInXmRO9JlhsMJ6OMSA9w=,iv:QNfG7XGW5J5SIHfvMso00RXHCl3oEa7X299aE2ZwK58=,tag:jpruuVY/j0S6BXZ8TmmanA==,type:time]
        public_key: ENC[AES256_GCM,data:JwCK5W/toZPbbUJeUR6SXYYGxCb69l9946yjj/KLduOUpQwRXYI6kDhhJYbuYI1Xp6Ldyr+miPgVdrW8noGkkVjXQS5/JKHpwOMn/7G/gLvb1dHLR8dpNOzm5It5EpqppoN265lnOQeqsCQSTWnrLp4ik1llEtxyVbSmlbMjFn4anbrnpaw6Qg==,iv:No3UywZciRumC/+RtSdTpnD2D24KqwXhwE1HaCQkL+k=,tag:UuxQwTJ2Y4+6iHHijqzGGw==,type:str]
        private_key: ENC[AES256_GCM,data:jJxepaBHvfNbb87IXRqolIh9zcEWUzIrWOmzMC8Fw3GC5vSNdsACPayNkFOcpQc818J1h7gHzdwixwKYImr9CQArG3OCrIc3w1BVkAaaIEbkBI+aLiGfujodN3zBPU0SObK8L8FXFGC0QAL0C0UBjPXO5PB6cyKhBbtScq6HsRlcLZdzmjjOVrIj0mrsJ1Eem6Vs6R68ASr7+OXsKhc8QIYJhdyz6AiCSZku7yw7M0B20SM7E5yn1LA5MZc9VYvwXDqr7JvVAqKYKKGtJZknDn+Fp3bOTIaljyBpBuG9qVtNsGF3sDuCisPY3jJHvwjpg4aSxHVaiDodJSgFxh8+qbyBdNUAFC9O7xmiBbsWAklwVB6vNVmqOx1le2b25jk8APzUOVOi0ISvOdqqU7kLaxGsd4C4vrs5KELVmtPYml40OPLqbj3qkD08sTo9MxlOarQAxQTNK3OdC/r7z6xtIJFEK8v0hO5ILfGd25c5NpGqzG637ZSyGJDjR4irgzFAm73Gqm5Ega4BMMnfVcPR/20Q2lWhiH5j5f5gYXX53vE+ycywUMKxcvgWw4ulpjHFV0lcQ3VI75hXsN/+87iGBCRYjnboSLP9mRLJCClPhcw=,iv:DXIwiInTj/SotmWheUbdTSC0wpsTxfgLQzhBmngZ2EQ=,tag:Zi8W2TMPmdUI/u/yvPvKPw==,type:str]
sops:
    age:
        - recipient: age1uy27rg7l9ql0z5uze4m969sarzl3dhjlzsty9g6xsl4542kh9yzqsleu5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TFBXTTRVS0Q5Z2g0VmFH
            aXAyMmx5cVY1UHZCMGVLZ3FsclBFK3ZqY1JBCk1vZnZMU0lPbkxlYUhVdENRNjFU
            Y3JEL0MrVHhKL1Z1M0M2cU9GdmQyQ2cKLS0tIFYxY2VCc2Y2UFhsZEMrbFVLb090
            QUxHNzlTY3dKNnJobW9tOFNleHhuV3cK4KUr7xbfRvSLj/4869H/Tw5z+lNJNaAs
            RiueTpnS+LwAiU/ZP6YBLd63Wb+OB8S4e1pTbXsProBykaPL/MKWAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-11T18:12:19Z"
    mac: ENC[AES256_GCM,data:H+wjSELl7Dbg+H/X0pWzLi2TmZMF6uP1b4Y4beTk7nDoKuZSZf+mSNRJ6B80tkq8q+IOKbQ82GhvEqKPY4eTTGUAG7aRKHLfLW3BWd50nWajFC0P6WiUu1Pn8k9EE0k+LBHWW076wCmHDnkEZNPSv8GG8kZwOqK0ZcHYdJgv2rY=,iv:N3IhocmeoAGnc8hgPNu3MyknXTA1LU6Z7Wi21JOd8CA=,tag:3Gkwh5A0LJOZ5uv9mHcp7Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
