vmid: 1006
description: Infrastructure VLAN internal ingress VM
placement:
  host: straylight
source:
  template: debian-13-base
hardware:
  cores: 1
  memory: 1024
  disks:
    - storage: local-lvm
      size: 16G
network:
  interfaces:
    - bridge: vmbr0
      vlan: 40
      address: 10.40.0.16/24
      gateway: 10.40.0.1
cloud_init:
  hostname: internal-ingress-vm
backup:
  enabled: true
ssh_public_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP/5oDWOUNo4lHbQfoa4uOPSEzbFqu59/5bvaD1/uX8i fortress-vm-prepare:internal-ingress-vm:2026-05-11T19:46:52Z
