ssh_keys:
    bootstrap:
        type: ENC[AES256_GCM,data:8pl0mIRE,iv:e7qXCk5F9m99DEDSV4vJhgQSVPp828CIxA7jCb9HUWw=,tag:XojAHmgBKOfsqgnYh/lYuA==,type:str]
        created: ENC[AES256_GCM,data:siutK6Uydn5ZSIhu+jIn4cIVX3w=,iv:HmqI1Lt4IqlWJewgs2DyBoRWIl8VPXHc0/tzf/mvxGo=,tag:5tta5BIToEktucKwXbNI0g==,type:time]
        public_key: ENC[AES256_GCM,data:EFfBlm60WT2bFATAS7WIyZNDIXWqmo99s75gNvAl6thNG0E9KB8z9NLcKaJq4DcQIQ83kr3WNYao1joJP1JwlQvxR33E/KeyIqLwOXxwfeZC0KxQO+34dmWESBjHgFNz+jzB+D1rFC9XOhLu63JneZTYMzFzDeOgue10N1p40bedhWLPbCHW2Hg=,iv:ux/FfxWErJRYBuWtvGAPA5hU5FMzG6CNCwcSc2vcnS4=,tag:eHy3D9oDLCoI7O9zzt4I6Q==,type:str]
        private_key: ENC[AES256_GCM,data:j5KjNofvgHoApvAVZFL13vYXI+hlj/EdgSqSSlrEDPNzfJldp8Z3cset+8c+7yvy/CDs8tjJk5zaesu6vQQaoyC5Dr1xPcdklQbPy4ikrCa6PxYameC2jw8DHlRx9TC11OhViCcrXqBH3GRAHZRwWwwcyGcqki/2UK3iz7G9UDVCooPSgKackoyKz4srJx0HY2l9mMxcj/vcEH8i27KLHILmoZ7u8qbL7riKz3yGuWP5KcjrjquEKlqF5WgEZEEDGqI6tTkYvlF9t0AEWlSd4po2gqid7l9Rq/r3S4c+KBRolMQ+ISx6LAEkgmsrlC7mi2EaB2ykk5gpCDySWg4PwkXiDF1ZGVwr4VwlJpS08XbjO/4SxH9BLMbYQtP4MQ5XAnOCxPKtmk0fkXBjIZKsXJ19A4SRP4PE/7sDOikMfIRo9AcKE2OsBkQ5M545lbML8C7rrxv76Z6kSAZ7biYV5m3rWj7xJmDZGfy5btcwyitU2JLOmLMtgEba/nhVkC5jvfW67oxbUvwX4pFml5uYdAMvUneDyuI0rKxjDEL0wG6lQVOXMUPErIfsXG3lnF+duy37kic0r6q6dZWNkFq8IzmLL3c4aORbify+C9ler9Q=,iv:x/OeNFvcJjiIJbKZFS+8HycqIehZ1j6y904J2L+iZp8=,tag:MzxoIN6Fx26hhLO558V5XA==,type:str]
sops:
    age:
        - recipient: age1uy27rg7l9ql0z5uze4m969sarzl3dhjlzsty9g6xsl4542kh9yzqsleu5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWkgrL0hJa2puNlBIZVdB
            eEZKemg0VEVOUjZlYzdJSTJQR1Y3d3p4ZUZNCkdNTG1HSWdqUzloV2padnh4VzNl
            MVhBeksvdlQ3MXByMGwzUFFjUGRYQlEKLS0tIFMxbVk1dEorZ1lHQktuZDhwcjBO
            MU11WmZMYzlxNEpBa3EyTkZ4eU9VdTQK+i05+e2gM/AHLxtREr/nfMUEJBO+lcH/
            kWkD5SbS52wFYZKEa4uILGuMJA9Kyrzw1Ddm/1cXcFuwwwQUHfFyZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T04:25:15Z"
    mac: ENC[AES256_GCM,data:lHDROqXZyRQFbvUKeyd1+ZXmyj9QJY0s4G3IN6bWjmO9ORNtHDHqR1I+GGRK9VwsFVBm3q/sNDPMCEo3N9IVmTYnogXbK5K/o7USvbjTHuB7PWe5pW39FRGYrOgfaWciB0ZMc+MVptOzufsw4hA8pEqE1XldM/qotpxKjPzb/RQ=,iv:146O+UoJyMllIIcroXMDV0n+eGKWPOBdTeR+amg/A0A=,tag:UzfZVflSdDPeigLvmhrzAQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
