import argparse
import json
import re
import sys
from pathlib import Path

from fortress_inventory.model import load_inventory_tree


HEADER = "# Generated by scripts/tofu-generate. Do not edit by hand.\n\n"


def generate_tofu(root, selected_vm=None):
    root = Path(root)
    model = load_inventory_tree(root)
    hosts = model.hosts
    if selected_vm:
        hosts = _selected_vm_hosts(model, selected_vm)
    errors = validate_provider_coverage(model)
    if errors:
        raise TofuGenerationError("\n".join(errors))
    tofu_root = root / "tofu"
    tofu_root.mkdir(exist_ok=True)
    (tofu_root / "generated-providers.tf").write_text(render_provider_hcl(hosts))
    (tofu_root / "generated-vm-partitions.tf").write_text(render_vm_partitions_hcl(hosts, selected_vm))


class TofuGenerationError(Exception):
    pass


def _selected_vm_hosts(model, selected_vm):
    if selected_vm not in model.vms:
        raise TofuGenerationError(f"selected_vm {selected_vm!r} is not declared in Inventory")
    host_name = model.vms[selected_vm].get("placement", {}).get("host")
    if host_name not in model.hosts:
        raise TofuGenerationError(
            f"missing_host_provider: VM {selected_vm} placement.host {host_name} has no generated Host provider"
        )
    return {host_name: model.hosts[host_name]}


def validate_provider_coverage(model):
    errors = []
    for vm_name, vm in sorted(model.vms.items()):
        host_name = vm.get("placement", {}).get("host")
        if host_name and host_name not in model.hosts:
            errors.append(
                f"missing_host_provider: VM {vm_name} placement.host {host_name} has no generated Host provider"
            )
    return errors


def render_provider_hcl(hosts):
    blocks = [HEADER]
    for host_name, host in sorted(hosts.items()):
        alias = hcl_identifier(host_name)
        token_var = f"pve_token_{alias}"
        ssh_key_var = f"pve_ssh_private_key_{alias}"
        endpoint = _host_endpoint(host)
        node_name = host.get("proxmox", {}).get("pve_node_name", host_name)
        node_address = host.get("network", {}).get("management_address", node_name)
        blocks.append(
            "\n".join(
                [
                    f'variable "{token_var}" {{',
                    "  type      = string",
                    "  sensitive = true",
                    "}",
                    "",
                    f'variable "{ssh_key_var}" {{',
                    "  type      = string",
                    "  sensitive = true",
                    "}",
                    "",
                    'provider "proxmox" {',
                    f'  alias     = "{alias}"',
                    f'  endpoint  = "{endpoint}"',
                    "  insecure  = true",
                    f"  api_token = var.{token_var}",
                    "",
                    "  ssh {",
                    '    username    = "root"',
                    f"    private_key = var.{ssh_key_var}",
                    "",
                    "    node {",
                    f'      name    = "{node_name}"',
                    f'      address = "{node_address}"',
                    "    }",
                    "  }",
                    "}",
                    "",
                ]
            )
        )
    return "\n".join(blocks)


def render_vm_partitions_hcl(hosts, selected_vm=None):
    blocks = [HEADER]
    for host_name, host in sorted(hosts.items()):
        alias = hcl_identifier(host_name)
        if selected_vm:
            vm_filter = f"vm_name == {json.dumps(selected_vm)}"
        else:
            vm_filter = f'vm.placement.host == "{host_name}"'
        blocks.append(
            "\n".join(
                [
                    f'module "vms_{alias}" {{',
                    '  source = "./modules/vm-partition"',
                    "",
                    "  providers = {",
                    f"    proxmox = proxmox.{alias}",
                    "  }",
                    "",
                    f'  host_name     = "{host_name}"',
                    f'  pve_node_name = "{host.get("proxmox", {}).get("pve_node_name", host_name)}"',
                    "  admin_user    = local.globals.vm_admin_user",
                    "  templates     = local.templates",
                    "  vms = {",
                    f"    for vm_name, vm in local.vms : vm_name => vm if {vm_filter}",
                    "  }",
                    "}",
                    "",
                ]
            )
        )
    return "\n".join(blocks)


def hcl_identifier(value):
    identifier = re.sub(r"[^A-Za-z0-9_]", "_", value)
    if not re.match(r"^[A-Za-z_]", identifier):
        identifier = f"host_{identifier}"
    return identifier


def _host_endpoint(host):
    proxmox = host.get("proxmox", {})
    if proxmox.get("endpoint"):
        endpoint = proxmox["endpoint"]
        if endpoint.startswith("http://"):
            return f"https://{endpoint.removeprefix('http://')}"
        return endpoint
    address = host.get("network", {}).get("management_address")
    if address:
        return f"https://{address}:8006"
    return f'https://{proxmox.get("pve_node_name", "proxmox")}:8006'


def main(argv=None):
    parser = argparse.ArgumentParser(description="Generate ignored OpenTofu HCL from fortress Inventory.")
    parser.add_argument("root", nargs="?", default=".", help="repository or fixture root")
    parser.add_argument("--selected-vm", help="generate provider coverage only for this VM's Host")
    args = parser.parse_args(argv)
    try:
        generate_tofu(args.root, selected_vm=args.selected_vm)
    except TofuGenerationError as error:
        print(error, file=sys.stderr)
        return 1
    return 0
