secrets:
    demo_password: ENC[AES256_GCM,data:NXAbBffru1BXY7QSAUufrre+k8wSf1qtU0oL5QO7Z5TQoAk2nLoa,iv:odgKDBxl7mcuxQqZHuX3rTr+gutoQS6PWQmAYAcaUeI=,tag:HUWCQEgvjxaXk45wPlsR8A==,type:str]
sops:
    age:
        - recipient: age1uy27rg7l9ql0z5uze4m969sarzl3dhjlzsty9g6xsl4542kh9yzqsleu5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeXlBamQ3ZVlNUEVSWG5q
            eTlRSVdQNVd1TW0vRXlKQ1ZaSjQ1NGhSMzBJCnorekJNcGl6SERFVjlFb2k0eVov
            UUxQdzkrQUdGMHlKSnZuNE9LUHlmRmcKLS0tIGRPN0NvOGhUUTZkQndZYitySUlH
            U1ZVRDFsTU56c2lKcGRid3ZQcHByUTgKIZKh+uG0A/Wt/bAeF/yIWFxqXIixWsno
            LV17+2YZ78Ee/MWaUhSvFj8VawbGWfSvM3dlXnCP5Ib20/NRuroRfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-10T17:40:07Z"
    mac: ENC[AES256_GCM,data:QqO15Higa8WAvEID/UUKp0p2+63n1K3Sl/e07RPfGfo8GCF8uBK3G4UDUGkOXXEuXORkRgm9U9xH1G6dg+VnwXu2OyakD95PveqnwCWK4CfkI6FzkvquFtwfOW38Bh1vg15aNsHlfjX0wmfW7bB+Sv2+P5ti0SKAm1YYgl9P+C8=,iv:SqhXHJgBG3loyHCspMj2cIDXgYKviteoCvzLeTpREEk=,tag:HkA226HC7hfS3LkjDBeosQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
