api_credentials:
    reconcile:
        type: ENC[AES256_GCM,data:M+ft0ijjU+i+j0aHE0Cl,iv:TgfsaQGGWKCMzujO6qP7tWippToTMUqFX+XaVYw3iUA=,tag://+l5OeiUmDUwgOsXMzU8w==,type:str]
        value: ENC[AES256_GCM,data:ZaSREWVPPi8tms09TU4KqPDiyPAgunkHJxEtjQd0Ly+mTGjN8J03hGvKCp2WrIy4cfYxeFER1qUHRlWm+u3e+U+0,iv:rJfIhAThO2E6IJU9D3LvwMU4cYJiA9bDRZXJQinp0t8=,tag:fmbZCC9AL6mWSWBFupvuMQ==,type:str]
    acceptance:
        type: ENC[AES256_GCM,data:eQUsN3bPa4gQ5/i4kkqK,iv:y+YWWnnGU7depDkyxOI9noQObBbo6ri+YmBEfjG5psE=,tag:0370XGX3uJBt4G4XBrPEWg==,type:str]
        value: ENC[AES256_GCM,data:MGRxOdU8H5b+uBALg5wdOmyFlizyk1CgEsFfnC0NsD/KOq/zb5n/fE1uHqp+6QNv6u5VAcPi6xcyca3JumW4ixpY,iv:wllbphXD40ogYT80KsxVFKPf8rfiR74X7PI02MoF0bY=,tag:UwAF3bjkKorE4Mg9XB1NBg==,type:str]
sops:
    age:
        - recipient: age1uy27rg7l9ql0z5uze4m969sarzl3dhjlzsty9g6xsl4542kh9yzqsleu5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WE4yaHBlTEJHTGtyNEQ4
            WDJkcytnQVNCUkNhZXVyM3lMQkVXN1V2YlU0CnQrZU9wdWp6K3l4emc4ZjhZZUx1
            Ny84NmRwU1htc29NaERxaW51b3NGRm8KLS0tIGJCZUovcTVaWVEyb2Y0R3g4Ykll
            ZVVJemxmaVR2eHAwbHlKbzE1VHJnZmcKvG7Bv9uvcr8CiRzIjyJRZpQECbNCmmML
            COqYJssLsMOtRZv0Bl64CigXNacKzEcmjWFZNyJkUmtizK6jmEJ47Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T20:26:01Z"
    mac: ENC[AES256_GCM,data:IEzp8iaoQOL748OvyV8ZdbugCsvV4ywiVtq+ti8SlZgvi7RGNe9gmhujlP7btd/6umd6q5uwbKI8YVg463TV8ceGVWx/IefAoIstlBUoHe2pQ3sVmXkvgaJlVBT1P007HBHbcZ8IjVCIlKctU9Te6C2Vw6l6ozg3vtbDh68P7mA=,iv:cDNXly2sN4UwfGDNZjPIT6ENmjFNrVX35EcqyM3zhnI=,tag:V21dCtXvVFm255dD3ZhABg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
