api_credentials:
    reconcile:
        type: ENC[AES256_GCM,data:M+ft0ijjU+i+j0aHE0Cl,iv:TgfsaQGGWKCMzujO6qP7tWippToTMUqFX+XaVYw3iUA=,tag://+l5OeiUmDUwgOsXMzU8w==,type:str]
        value: ENC[AES256_GCM,data:Y/Ms+SNHBZEM151wFIbYeyy70UooEZj0g7n2nT/6NEgO43UawiKZ5gZqPA2ojcy08rRai9N1b6mQikwMf56xSOO1,iv:0jUbpZcOUwM8rE1alTJ/6/KpTw3PcV+dqWIgGm57gho=,tag:ay+PqphEjmgM7o6rlmG6ug==,type:str]
    acceptance:
        type: ENC[AES256_GCM,data:eQUsN3bPa4gQ5/i4kkqK,iv:y+YWWnnGU7depDkyxOI9noQObBbo6ri+YmBEfjG5psE=,tag:0370XGX3uJBt4G4XBrPEWg==,type:str]
        value: ENC[AES256_GCM,data:MGRxOdU8H5b+uBALg5wdOmyFlizyk1CgEsFfnC0NsD/KOq/zb5n/fE1uHqp+6QNv6u5VAcPi6xcyca3JumW4ixpY,iv:wllbphXD40ogYT80KsxVFKPf8rfiR74X7PI02MoF0bY=,tag:UwAF3bjkKorE4Mg9XB1NBg==,type:str]
sops:
    age:
        - recipient: age1uy27rg7l9ql0z5uze4m969sarzl3dhjlzsty9g6xsl4542kh9yzqsleu5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WE4yaHBlTEJHTGtyNEQ4
            WDJkcytnQVNCUkNhZXVyM3lMQkVXN1V2YlU0CnQrZU9wdWp6K3l4emc4ZjhZZUx1
            Ny84NmRwU1htc29NaERxaW51b3NGRm8KLS0tIGJCZUovcTVaWVEyb2Y0R3g4Ykll
            ZVVJemxmaVR2eHAwbHlKbzE1VHJnZmcKvG7Bv9uvcr8CiRzIjyJRZpQECbNCmmML
            COqYJssLsMOtRZv0Bl64CigXNacKzEcmjWFZNyJkUmtizK6jmEJ47Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-08T21:09:18Z"
    mac: ENC[AES256_GCM,data:7Ely2VKexjhhsu5AyoTpSVSQAwvWTrTN/oMka9K3B5OvHd20+Y3gh6q0qn9aXDU11yLMaM9slS5Cst6etHpC7uFBgL5Hss8I0K7ffAcO8e6UPaWJ4nUVw3AmRXaBcBVHuEaeNZ6GXlryop3f/pH98zbAcn3NgQBKcSDTb6mW1qA=,iv:r9gxCzGlsltkr5hprta9VbWFZtTE1Ksm5Tt4m5CmaWI=,tag:3V8lm5RWO+35T9jSKCgKGg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
