domain: fearn.cloud
timezone: UTC
ntp_servers:
  - time.cloudflare.com
dns_resolvers:
  - 1.1.1.1
  - 1.0.0.1
vm_admin_user: admin
nas:
  default_options:
    - nfsvers=4.2
    - soft
    - _netdev
  uid_gid_map:
    test:
      uid: 1000
      gid: 1000
apt_repos:
  caddy_official:
    url: https://dl.cloudsmith.io/public/caddy/stable/deb/debian
    repo: deb [trusted=yes] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
  proxmox_backup_no_subscription:
    url: http://download.proxmox.com/debian/pbs
    repo: deb [trusted=yes] http://download.proxmox.com/debian/pbs trixie pbs-no-subscription
