domain: fearn.cloud
timezone: UTC
ntp_servers:
  - time.cloudflare.com
dns_resolvers:
  - 1.1.1.1
  - 1.0.0.1
vm_admin_user: admin
nas:
  endpoints:
    truenas:
      address: 10.40.0.15
  server: 10.40.0.15
  default_options:
    - nfsvers=4.2
    - soft
    - _netdev
  exports:
    test: /mnt/tank/test
  uid_gid_map:
    test:
      uid: 1000
      gid: 1000
apt_repos:
  caddy_official:
    url: https://dl.cloudsmith.io/public/caddy/stable/deb/debian
